# Nome do fluxo de trabalho que aparecerá no separador "Actions" do GitHub
name: Validação de Build e Testes em Java

# Define quando este fluxo de trabalho deve ser executado
on:
  # Executa em CADA push, EXCETO para as branches main e develop
  push:
    branches-ignore:
      - 'main'
      - 'develop'
  # Também executa quando um Pull Request é aberto PARA as branches main ou develop
  pull_request:
    branches:
      - 'main'
      - 'develop'

# Define os trabalhos (jobs) que o fluxo de trabalho irá realizar
jobs:
  build-and-test:
    # O tipo de máquina virtual onde o trabalho será executado
    runs-on: ubuntu-latest

    # A sequência de passos que o nosso job irá executar
    steps:
      # 1. Faz o checkout do seu código do repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o ambiente Java (JDK) na máquina virtual
      - name: Configurar o Java JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"

      # 3. Dá permissão de execução ao Maven Wrapper
      - name: Dar permissão de execução ao mvnw
        run: chmod +x ./mvnw

      # 4. Executa o seu script de validação completo
      - name: Executar o script de validação (Build e Testes)
        run: ./validate-pr.sh
